### ISSUE TITLE
Bottomless fluids not working

### ISSUE THREAD

**Issue by EricBuist** [adamico/mechanical-mastery-plus#158]
### Which OS are you using?

WINDOWS

### Which Launcher?

CurseForge

### Describe the bug

I placed 10,000 blocks of liquid D-T Fuel in a 25x16x25 volume (using RFTools Builder+place fluid card), installed a Create hoose pulley on top, brought the hoose down into the liquid and used a mechanical pump to transfer fluid from the pool to a supreme black hole tank, using Create's fluid pipes. At first, the target fluid wasn't infinite. I reversed the pump to add some extra buckets of liquid into the pool, fluid volume became bottomless, so I reversed the pump to add to the black hole tank. The pumping is slow, even at max 256rpm, and at some point, the target volume becomes finite again.
This makes the final quest nearly impossible, requiring once again to start a server and let it run for days, if not weeks. This is a growing trend for a lot of modpack to put an impossible endgame requiring a server, and I really dislike it. It is time consuming to create a server with ability to auto restart, auto backup, etc., and this is wasting CPU cycle to let a server just run a game to get ridicously large amounts of items or fluids. Spending weeks repeating the same contraption again, again, again and again to amp up production of an item or fluid is also a waste of time. If there was beter copy/pasting abilities for contraption like Factorio provides, that would be more achievable to create large scale factories duplicating the same complex builds tens, if not 50s of times, but not if I have to place down all the blocks, pipes, etc. manually.
That could have been solved by requesting only 10,000 buckets of every fluid, or provide a recipe for a creative fluid tank.

### To reproduce

1. Start Launcher
2. Install or Start Mechanical Mastery Plus
3. Create / Load World / join server
4. Place a 25x16x25 volume of liquid DT Fuel in the world.
5. Put a hoose pulley on top of the pool
6. Add fluid pipes, mechanical pump, fluid pipe, tank.
7. Pull down the pulley into fluid, using e.g. hand crank.
8. Provide energy to mechanical pump using e.g. elctric motor+flux point (assuming there is a power source providing energy into flux network)
9. Observe the non-bottomless volume.
10. Reverse pump until volume becomes bottomless.
11. Reverse pump and let fluid transfer to tank.
12. Observe the pulley becoming non-bottomless.
13. Be prepared for a lot of work, need 2B buckets produced using isotropic centrifuge...

### Expected behavior

Fluid volume should be infinite, and it should be possible to pipe fluid until a supreme black hole tank is full.

### Logs

**latest.log**:

**crashlog**: 
This is not a crash.

**Comment by sharkman** [comment]
I have a similar issue with 10x10x100 pool of darkness essence, except it _never_ becomes bottomless.

Steps to reproduce the behavior:

1. Start Launcher
2. Install or Start Mechanical Mastery Plus
3. Create / Load World / join server
4. Create a pool 10x10x100 in size to hold the darkness essence.
5. Put a hoose pulley on top of the pool
6. Add fluid pipes, mechanical pump, fluid pipe, tank.
7. Pull down the pulley into the pool (position 1 for filling, just 1 block deep into the future top of the fluid pool).
8. Place a 10x10x100 volume of darkness essence in the world using the mechanical pump + hoose pulley.
9. Place the last bucket manually, because for whatever reason it can't place the last bucket in the S-W corner of the pool.
10. Reverse the pump.
11. Observe the non-bottomless volume.
12. Pull down the pulley into the pool (position 2 for emptying, into the bottom of the pool).
13. Observe the non-bottomless volume anyway.
14. ???

**Comment by sharkman** [comment]
ok, adding an additional layer to the pool works fine, e.g., 10x10x101 or 25x25x17 pool size.

**Comment by EricBuist** [comment]
I suspect the pulley cannot be water logged or the pulley block doesn't count as a fluid block. A pool of 25x16x25 will thus have 10000-16 fluid blocks, so an extra layer solves the problem. Additionally, I had to put the hose pulley at the center of the pool and lower the pulley at the very bottom of the pool for the fluid to be and stay infinite. I now have infinite quantity of the 5 fluids needed for the final quest, but pumping is too slow so it would take days if not weeks to completely fill up supreme black hole tanks.

**Comment by sharkman** [comment]
this still need to be fixed on create side
